// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAARruALAJhslaG1n8jZddtZxnJszhTqS4',
    appId: '1:1084046277762:web:2b4b6e9105517ccecc489b',
    messagingSenderId: '1084046277762',
    projectId: 'homzes-flutter-917f0',
    authDomain: 'homzes-flutter-917f0.firebaseapp.com',
    storageBucket: 'homzes-flutter-917f0.firebasestorage.app',
    measurementId: 'G-GSG7997SPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlzlG3SBaJK3relqDnemHxXWNbUbQV7-s',
    appId: '1:1084046277762:android:ee9cf0b781f46ff8cc489b',
    messagingSenderId: '1084046277762',
    projectId: 'homzes-flutter-917f0',
    storageBucket: 'homzes-flutter-917f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDskRpI0yJSy37pxhyc7r3aW-VXVtDv9Ss',
    appId: '1:1084046277762:ios:2f4564d57d2150aacc489b',
    messagingSenderId: '1084046277762',
    projectId: 'homzes-flutter-917f0',
    storageBucket: 'homzes-flutter-917f0.firebasestorage.app',
    iosBundleId: 'com.example.homzes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDskRpI0yJSy37pxhyc7r3aW-VXVtDv9Ss',
    appId: '1:1084046277762:ios:2f4564d57d2150aacc489b',
    messagingSenderId: '1084046277762',
    projectId: 'homzes-flutter-917f0',
    storageBucket: 'homzes-flutter-917f0.firebasestorage.app',
    iosBundleId: 'com.example.homzes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAARruALAJhslaG1n8jZddtZxnJszhTqS4',
    appId: '1:1084046277762:web:18c9bf346faadd3fcc489b',
    messagingSenderId: '1084046277762',
    projectId: 'homzes-flutter-917f0',
    authDomain: 'homzes-flutter-917f0.firebaseapp.com',
    storageBucket: 'homzes-flutter-917f0.firebasestorage.app',
    measurementId: 'G-B5RJ2QLLS4',
  );

}